Repository ayushicoder18/hacked-server, pull requests merged in 2022-10, with the labels that each got.

#1 manual setup for server
  tasks/nodemon.js
Labels: good first issue, hacktoberfest-accepted

#2 Create router.js
  client/router.js
  modules/frontPage/client.js
Labels: documentation, hacktoberfest-accepted

#3 Update client.js
  modules/frontPage/client.js
Labels: documentation, good first issue, hacktoberfest-accepted

#4 Update react.js
  assests/libraries/react.js
Labels: hacktoberfest-accepted

#5 Create database.js
  server/database.js
Labels: enhancement, hacktoberfest-accepted

#6 Create docker.py
  py-files/docker.py
Labels: documentation, good first issue, hacktoberfest-accepted
